lsi: false
safe: true
source: .
title: Onion's Life
tagline: An EPIC game for web where you impersonate an Onion and go on adventures through mazes and labyrinths.
logo: /assets/sprites/onion.png
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
